<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T06_cost_model extends CI_Model
{

    public $table = 't06_cost';
    public $id = 'idcost';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idcost,cost,idakun');
        $this->datatables->from('t06_cost');
		if (isset($_POST['idcost']) && $_POST['idcost'] != '') { $this->datatables->like('idcost', $_POST['idcost']); }
		if (isset($_POST['cost']) && $_POST['cost'] != '') { $this->datatables->like('cost', $_POST['cost']); }
		if (isset($_POST['idakun']) && $_POST['idakun'] != '') { $this->datatables->like('idakun', $_POST['idakun']); }
        //add this line for join
        //$this->datatables->join('table2', 't06_cost.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t06_cost/update/$1'),'Ubah')." | ".anchor(site_url('t06_cost/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idcost');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idcost', $q);
		$this->db->or_like('cost', $q);
		$this->db->or_like('idakun', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idcost', $q);
		$this->db->or_like('cost', $q);
		$this->db->or_like('idakun', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T06_cost_model.php */
/* Location: ./application/models/T06_cost_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 23:39:35 */
/* http://harviacode.com */