<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T03_lokasi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T03_lokasi_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t03_lokasi/t03_lokasi_list');
        $data['_view'] = 't03_lokasi/t03_lokasi_list';
        $data['_caption'] = 'Lokasi';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T03_lokasi_model->json();
    }

    public function read($id)
    {
        $row = $this->T03_lokasi_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idlokasi' => $row->idlokasi,
				'lokasi' => $row->lokasi,
	    	);
            $this->load->view('t03_lokasi/t03_lokasi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t03_lokasi'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t03_lokasi/create_action'),
		    'idlokasi' => set_value('idlokasi'),
		    'lokasi' => set_value('lokasi'),
		);
        // $this->load->view('t03_lokasi/t03_lokasi_form', $data);
        $data['_view'] = 't03_lokasi/t03_lokasi_form';
        $data['_caption'] = 'Lokasi';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'lokasi' => $this->input->post('lokasi',TRUE),
	    	);
            $this->T03_lokasi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t03_lokasi'));
        }
    }

    public function update($id)
    {
        $row = $this->T03_lokasi_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t03_lokasi/update_action'),
				'idlokasi' => set_value('idlokasi', $row->idlokasi),
				'lokasi' => set_value('lokasi', $row->lokasi),
	    	);
            // $this->load->view('t03_lokasi/t03_lokasi_form', $data);
            $data['_view'] = 't03_lokasi/t03_lokasi_form';
            $data['_caption'] = 'Lokasi';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t03_lokasi'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idlokasi', TRUE));
        } else {
            $data = array(
				'lokasi' => $this->input->post('lokasi',TRUE),
	    	);
            $this->T03_lokasi_model->update($this->input->post('idlokasi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t03_lokasi'));
        }
    }

    public function delete($id)
    {
        $row = $this->T03_lokasi_model->get_by_id($id);
        if ($row) {
            $this->T03_lokasi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t03_lokasi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t03_lokasi'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('lokasi', 'lokasi', 'trim|required');
		$this->form_validation->set_rules('idlokasi', 'idlokasi', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T03_lokasi.php */
/* Location: ./application/controllers/T03_lokasi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 17:42:22 */
/* http://harviacode.com */