<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T07_service_model extends CI_Model
{

    public $table = 't07_service';
    public $id = 'idservice';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idservice,service');
        $this->datatables->from('t07_service');
		if (isset($_POST['idservice']) && $_POST['idservice'] != '') { $this->datatables->like('idservice', $_POST['idservice']); }
		if (isset($_POST['service']) && $_POST['service'] != '') { $this->datatables->like('service', $_POST['service']); }
        //add this line for join
        //$this->datatables->join('table2', 't07_service.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t07_service/update/$1'),'Ubah')." | ".anchor(site_url('t07_service/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idservice');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idservice', $q);
		$this->db->or_like('service', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idservice', $q);
		$this->db->or_like('service', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T07_service_model.php */
/* Location: ./application/models/T07_service_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 23:51:09 */
/* http://harviacode.com */