<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T03_lokasi_model extends CI_Model
{

    public $table = 't03_lokasi';
    public $id = 'idlokasi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idlokasi,lokasi');
        $this->datatables->from('t03_lokasi');
		if (isset($_POST['idlokasi']) && $_POST['idlokasi'] != '') { $this->datatables->like('idlokasi', $_POST['idlokasi']); }
		if (isset($_POST['lokasi']) && $_POST['lokasi'] != '') { $this->datatables->like('lokasi', $_POST['lokasi']); }
        //add this line for join
        //$this->datatables->join('table2', 't03_lokasi.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t03_lokasi/update/$1'),'Ubah')." | ".anchor(site_url('t03_lokasi/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idlokasi');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idlokasi', $q);
		$this->db->or_like('lokasi', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idlokasi', $q);
		$this->db->or_like('lokasi', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T03_lokasi_model.php */
/* Location: ./application/models/T03_lokasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 17:42:22 */
/* http://harviacode.com */