<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T07_service extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T07_service_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t07_service/t07_service_list');
        $data['_view'] = 't07_service/t07_service_list';
        $data['_caption'] = 'Service';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T07_service_model->json();
    }

    public function read($id)
    {
        $row = $this->T07_service_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idservice' => $row->idservice,
				'service' => $row->service,
	    	);
            $this->load->view('t07_service/t07_service_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t07_service'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t07_service/create_action'),
		    'idservice' => set_value('idservice'),
		    'service' => set_value('service'),
		);
        // $this->load->view('t07_service/t07_service_form', $data);
        $data['_view'] = 't07_service/t07_service_form';
        $data['_caption'] = 'Service';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'service' => $this->input->post('service',TRUE),
	    	);
            $this->T07_service_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t07_service'));
        }
    }

    public function update($id)
    {
        $row = $this->T07_service_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t07_service/update_action'),
				'idservice' => set_value('idservice', $row->idservice),
				'service' => set_value('service', $row->service),
	    	);
            // $this->load->view('t07_service/t07_service_form', $data);
            $data['_view'] = 't07_service/t07_service_form';
            $data['_caption'] = 'Service';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t07_service'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idservice', TRUE));
        } else {
            $data = array(
				'service' => $this->input->post('service',TRUE),
	    	);
            $this->T07_service_model->update($this->input->post('idservice', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t07_service'));
        }
    }

    public function delete($id)
    {
        $row = $this->T07_service_model->get_by_id($id);
        if ($row) {
            $this->T07_service_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t07_service'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t07_service'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('service', 'service', 'trim|required');
		$this->form_validation->set_rules('idservice', 'idservice', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T07_service.php */
/* Location: ./application/controllers/T07_service.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 23:51:09 */
/* http://harviacode.com */