<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T06_cost extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T06_cost_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t06_cost/t06_cost_list');
        $data['_view'] = 't06_cost/t06_cost_list';
        $data['_caption'] = 'Cost';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T06_cost_model->json();
    }

    public function read($id)
    {
        $row = $this->T06_cost_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idcost' => $row->idcost,
				'cost' => $row->cost,
				'idakun' => $row->idakun,
	    	);
            $this->load->view('t06_cost/t06_cost_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t06_cost'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t06_cost/create_action'),
		    'idcost' => set_value('idcost'),
		    'cost' => set_value('cost'),
		    'idakun' => set_value('idakun'),
		);
        // $this->load->view('t06_cost/t06_cost_form', $data);
        $data['_view'] = 't06_cost/t06_cost_form';
        $data['_caption'] = 'Cost';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'cost' => $this->input->post('cost',TRUE),
				'idakun' => $this->input->post('idakun',TRUE),
	    	);
            $this->T06_cost_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t06_cost'));
        }
    }

    public function update($id)
    {
        $row = $this->T06_cost_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t06_cost/update_action'),
				'idcost' => set_value('idcost', $row->idcost),
				'cost' => set_value('cost', $row->cost),
				'idakun' => set_value('idakun', $row->idakun),
	    	);
            // $this->load->view('t06_cost/t06_cost_form', $data);
            $data['_view'] = 't06_cost/t06_cost_form';
            $data['_caption'] = 'Cost';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t06_cost'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idcost', TRUE));
        } else {
            $data = array(
				'cost' => $this->input->post('cost',TRUE),
				'idakun' => $this->input->post('idakun',TRUE),
	    	);
            $this->T06_cost_model->update($this->input->post('idcost', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t06_cost'));
        }
    }

    public function delete($id)
    {
        $row = $this->T06_cost_model->get_by_id($id);
        if ($row) {
            $this->T06_cost_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t06_cost'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t06_cost'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('cost', 'cost', 'trim|required');
		$this->form_validation->set_rules('idakun', 'idakun', 'trim|required');
		$this->form_validation->set_rules('idcost', 'idcost', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T06_cost.php */
/* Location: ./application/controllers/T06_cost.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 23:39:35 */
/* http://harviacode.com */