<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T99_company extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T99_company_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t99_company/t99_company_list');
        $data['_view'] = 't99_company/t99_company_list';
        $data['_caption'] = 'Company';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T99_company_model->json();
    }

    public function read($id)
    {
        $row = $this->T99_company_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idcompany' => $row->idcompany,
				'nama' => $row->nama,
				'alamat' => $row->alamat,
				'kota' => $row->kota,
	    	);
            $this->load->view('t99_company/t99_company_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t99_company'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t99_company/create_action'),
		    'idcompany' => set_value('idcompany'),
		    'nama' => set_value('nama'),
		    'alamat' => set_value('alamat'),
		    'kota' => set_value('kota'),
		);
        // $this->load->view('t99_company/t99_company_form', $data);
        $data['_view'] = 't99_company/t99_company_form';
        $data['_caption'] = 'Company';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'nama' => $this->input->post('nama',TRUE),
				'alamat' => $this->input->post('alamat',TRUE),
				'kota' => $this->input->post('kota',TRUE),
	    	);
            $this->T99_company_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t99_company'));
        }
    }

    public function update($id)
    {
        $row = $this->T99_company_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t99_company/update_action'),
				'idcompany' => set_value('idcompany', $row->idcompany),
				'nama' => set_value('nama', $row->nama),
				'alamat' => set_value('alamat', $row->alamat),
				'kota' => set_value('kota', $row->kota),
	    	);
            // $this->load->view('t99_company/t99_company_form', $data);
            $data['_view'] = 't99_company/t99_company_form';
            $data['_caption'] = 'Company';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t99_company'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idcompany', TRUE));
        } else {
            $data = array(
				'nama' => $this->input->post('nama',TRUE),
				'alamat' => $this->input->post('alamat',TRUE),
				'kota' => $this->input->post('kota',TRUE),
	    	);
            $this->T99_company_model->update($this->input->post('idcompany', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t99_company'));
        }
    }

    public function delete($id)
    {
        $row = $this->T99_company_model->get_by_id($id);
        if ($row) {
            $this->T99_company_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t99_company'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t99_company'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('nama', 'nama', 'trim|required');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|required');
		$this->form_validation->set_rules('kota', 'kota', 'trim|required');
		$this->form_validation->set_rules('idcompany', 'idcompany', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T99_company.php */
/* Location: ./application/controllers/T99_company.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-27 09:30:43 */
/* http://harviacode.com */