<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T02_vendor_model extends CI_Model
{

    public $table = 't02_vendor';
    public $id = 'idvendor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idvendor,nama,alamat,kota,contact_person,telepon');
        $this->datatables->from('t02_vendor');
		if (isset($_POST['idvendor']) && $_POST['idvendor'] != '') { $this->datatables->like('idvendor', $_POST['idvendor']); }
		if (isset($_POST['nama']) && $_POST['nama'] != '') { $this->datatables->like('nama', $_POST['nama']); }
		if (isset($_POST['alamat']) && $_POST['alamat'] != '') { $this->datatables->like('alamat', $_POST['alamat']); }
		if (isset($_POST['kota']) && $_POST['kota'] != '') { $this->datatables->like('kota', $_POST['kota']); }
		if (isset($_POST['contact_person']) && $_POST['contact_person'] != '') { $this->datatables->like('contact_person', $_POST['contact_person']); }
		if (isset($_POST['telepon']) && $_POST['telepon'] != '') { $this->datatables->like('telepon', $_POST['telepon']); }
        //add this line for join
        //$this->datatables->join('table2', 't02_vendor.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t02_vendor/update/$1'),'Ubah')." | ".anchor(site_url('t02_vendor/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idvendor');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idvendor', $q);
		$this->db->or_like('nama', $q);
		$this->db->or_like('alamat', $q);
		$this->db->or_like('kota', $q);
		$this->db->or_like('contact_person', $q);
		$this->db->or_like('telepon', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idvendor', $q);
		$this->db->or_like('nama', $q);
		$this->db->or_like('alamat', $q);
		$this->db->or_like('kota', $q);
		$this->db->or_like('contact_person', $q);
		$this->db->or_like('telepon', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T02_vendor_model.php */
/* Location: ./application/models/T02_vendor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 16:28:39 */
/* http://harviacode.com */