<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T05_satuan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('T05_satuan_model');
        $this->load->library('form_validation');        
		$this->load->library('datatables');
    }

    public function index()
    {
        // $this->load->view('t05_satuan/t05_satuan_list');
        $data['_view'] = 't05_satuan/t05_satuan_list';
        $data['_caption'] = 'Satuan';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function json() {
        header('Content-Type: application/json');
        echo $this->T05_satuan_model->json();
    }

    public function read($id)
    {
        $row = $this->T05_satuan_model->get_by_id($id);
        if ($row) {
            $data = array(
				'idsatuan' => $row->idsatuan,
				'satuan' => $row->satuan,
				'kode' => $row->kode,
				'tipe' => $row->tipe,
	    	);
            $this->load->view('t05_satuan/t05_satuan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t05_satuan'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Simpan',
            'action' => site_url('t05_satuan/create_action'),
		    'idsatuan' => set_value('idsatuan'),
		    'satuan' => set_value('satuan'),
		    'kode' => set_value('kode'),
		    'tipe' => set_value('tipe'),
		);
        // $this->load->view('t05_satuan/t05_satuan_form', $data);
        $data['_view'] = 't05_satuan/t05_satuan_form';
        $data['_caption'] = 'Satuan';
        $this->load->view('_00_dashboard/_00_dashboard', $data);
    }

    public function create_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
				'satuan' => $this->input->post('satuan',TRUE),
				'kode' => $this->input->post('kode',TRUE),
				'tipe' => $this->input->post('tipe',TRUE),
	    	);
            $this->T05_satuan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('t05_satuan'));
        }
    }

    public function update($id)
    {
        $row = $this->T05_satuan_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Simpan',
                'action' => site_url('t05_satuan/update_action'),
				'idsatuan' => set_value('idsatuan', $row->idsatuan),
				'satuan' => set_value('satuan', $row->satuan),
				'kode' => set_value('kode', $row->kode),
				'tipe' => set_value('tipe', $row->tipe),
	    	);
            // $this->load->view('t05_satuan/t05_satuan_form', $data);
            $data['_view'] = 't05_satuan/t05_satuan_form';
            $data['_caption'] = 'Satuan';
            $this->load->view('_00_dashboard/_00_dashboard', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t05_satuan'));
        }
    }

    public function update_action()
    {
        $this->_rules();
        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('idsatuan', TRUE));
        } else {
            $data = array(
				'satuan' => $this->input->post('satuan',TRUE),
				'kode' => $this->input->post('kode',TRUE),
				'tipe' => $this->input->post('tipe',TRUE),
	    	);
            $this->T05_satuan_model->update($this->input->post('idsatuan', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('t05_satuan'));
        }
    }

    public function delete($id)
    {
        $row = $this->T05_satuan_model->get_by_id($id);
        if ($row) {
            $this->T05_satuan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('t05_satuan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('t05_satuan'));
        }
    }

    public function _rules()
    {
		$this->form_validation->set_rules('satuan', 'satuan', 'trim|required');
		$this->form_validation->set_rules('kode', 'kode', 'trim|required');
		$this->form_validation->set_rules('tipe', 'tipe', 'trim|required');
		$this->form_validation->set_rules('idsatuan', 'idsatuan', 'trim');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file T05_satuan.php */
/* Location: ./application/controllers/T05_satuan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 22:20:01 */
/* http://harviacode.com */