<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T01_shipper_model extends CI_Model
{

    public $table = 't01_shipper';
    public $id = 'idshipper';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idshipper,nama,alamat,kota,contact_person,telepon');
        $this->datatables->from('t01_shipper');
		if (isset($_POST['idshipper']) && $_POST['idshipper'] != '') { $this->datatables->like('idshipper', $_POST['idshipper']); }
		if (isset($_POST['nama']) && $_POST['nama'] != '') { $this->datatables->like('nama', $_POST['nama']); }
		if (isset($_POST['alamat']) && $_POST['alamat'] != '') { $this->datatables->like('alamat', $_POST['alamat']); }
		if (isset($_POST['kota']) && $_POST['kota'] != '') { $this->datatables->like('kota', $_POST['kota']); }
		if (isset($_POST['contact_person']) && $_POST['contact_person'] != '') { $this->datatables->like('contact_person', $_POST['contact_person']); }
		if (isset($_POST['telepon']) && $_POST['telepon'] != '') { $this->datatables->like('telepon', $_POST['telepon']); }
        //add this line for join
        //$this->datatables->join('table2', 't01_shipper.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t01_shipper/update/$1'),'Ubah')." | ".anchor(site_url('t01_shipper/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idshipper');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idshipper', $q);
		$this->db->or_like('nama', $q);
		$this->db->or_like('alamat', $q);
		$this->db->or_like('kota', $q);
		$this->db->or_like('contact_person', $q);
		$this->db->or_like('telepon', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idshipper', $q);
		$this->db->or_like('nama', $q);
		$this->db->or_like('alamat', $q);
		$this->db->or_like('kota', $q);
		$this->db->or_like('contact_person', $q);
		$this->db->or_like('telepon', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T01_shipper_model.php */
/* Location: ./application/models/T01_shipper_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 06:27:43 */
/* http://harviacode.com */