<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T04_armada_model extends CI_Model
{

    public $table = 't04_armada';
    public $id = 'idarmada';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('idarmada,merk,tipe,tahun_pembuatan,nomor_polisi,nomor_rangka,nomor_mesin,tanggal_pembelian,tanggal_jatuh_tempo_pajak,tanggal_jatuh_tempo_kir');
        $this->datatables->from('t04_armada');
		if (isset($_POST['idarmada']) && $_POST['idarmada'] != '') { $this->datatables->like('idarmada', $_POST['idarmada']); }
		if (isset($_POST['merk']) && $_POST['merk'] != '') { $this->datatables->like('merk', $_POST['merk']); }
		if (isset($_POST['tipe']) && $_POST['tipe'] != '') { $this->datatables->like('tipe', $_POST['tipe']); }
		if (isset($_POST['tahun_pembuatan']) && $_POST['tahun_pembuatan'] != '') { $this->datatables->like('tahun_pembuatan', $_POST['tahun_pembuatan']); }
		if (isset($_POST['nomor_polisi']) && $_POST['nomor_polisi'] != '') { $this->datatables->like('nomor_polisi', $_POST['nomor_polisi']); }
		if (isset($_POST['nomor_rangka']) && $_POST['nomor_rangka'] != '') { $this->datatables->like('nomor_rangka', $_POST['nomor_rangka']); }
		if (isset($_POST['nomor_mesin']) && $_POST['nomor_mesin'] != '') { $this->datatables->like('nomor_mesin', $_POST['nomor_mesin']); }
		if (isset($_POST['tanggal_pembelian']) && $_POST['tanggal_pembelian'] != '') { $this->datatables->like('tanggal_pembelian', $_POST['tanggal_pembelian']); }
		if (isset($_POST['tanggal_jatuh_tempo_pajak']) && $_POST['tanggal_jatuh_tempo_pajak'] != '') { $this->datatables->like('tanggal_jatuh_tempo_pajak', $_POST['tanggal_jatuh_tempo_pajak']); }
		if (isset($_POST['tanggal_jatuh_tempo_kir']) && $_POST['tanggal_jatuh_tempo_kir'] != '') { $this->datatables->like('tanggal_jatuh_tempo_kir', $_POST['tanggal_jatuh_tempo_kir']); }
        //add this line for join
        //$this->datatables->join('table2', 't04_armada.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t04_armada/update/$1'),'Ubah')." | ".anchor(site_url('t04_armada/delete/$1'),'Hapus','onclick="javascript: return confirm(\'Apakah Anda yakin ingin menghapus data ?\')"'), 'idarmada');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idarmada', $q);
		$this->db->or_like('merk', $q);
		$this->db->or_like('tipe', $q);
		$this->db->or_like('tahun_pembuatan', $q);
		$this->db->or_like('nomor_polisi', $q);
		$this->db->or_like('nomor_rangka', $q);
		$this->db->or_like('nomor_mesin', $q);
		$this->db->or_like('tanggal_pembelian', $q);
		$this->db->or_like('tanggal_jatuh_tempo_pajak', $q);
		$this->db->or_like('tanggal_jatuh_tempo_kir', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idarmada', $q);
		$this->db->or_like('merk', $q);
		$this->db->or_like('tipe', $q);
		$this->db->or_like('tahun_pembuatan', $q);
		$this->db->or_like('nomor_polisi', $q);
		$this->db->or_like('nomor_rangka', $q);
		$this->db->or_like('nomor_mesin', $q);
		$this->db->or_like('tanggal_pembelian', $q);
		$this->db->or_like('tanggal_jatuh_tempo_pajak', $q);
		$this->db->or_like('tanggal_jatuh_tempo_kir', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T04_armada_model.php */
/* Location: ./application/models/T04_armada_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-29 20:11:34 */
/* http://harviacode.com */